Milista=["Jaime","Maria","Andrea","Marcela","Alejandra","Pablo"]
print(Milista)

print(Milista[2])
Milista[3]="Laura"
print(Milista)
Primos=[1,3,5,7,11,13,17]
#print(Primos[2]>=2)ss
print(Primos[0]==Primos[0])
print(Primos[0]==Primos[2])
print(Primos[1]!=Primos[0])
print(Primos[1]!=Primos[1])
print(Primos[2]>Primos[1])
print(Primos[2]>Primos[3])
print(Primos[3]<Primos[4])
print(Primos[3]<Primos[2])
print(Primos[4]>=Primos[4])
print(Primos[4]>=Primos[5])
print(Primos[5]<=Primos[5])
print(Primos[5]<=Primos[4])
Primos.append(19)
print(Primos)
